# -*- coding: utf-8 -*-
"""pcp_1sem_cp2_ex01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qH8N049p5C-pZZyYaTKMvns_NMBbGZTG

Exercício 1
"""

# PESO DA CARGA EM TONELADAS
peso_carga = float(input("Digite o peso da carga do caminhão em toneladas: "))
print(f"o peso é de {peso_carga} Toneladas")

# CONVERSÃO DO PESO(TONELADA -> CARGA)
peso_carga_kg = peso_carga * 1000
print(f"o peso da carga convertido é de {peso_carga_kg} KG")

# CÓDIGO DA CARGA E PREÇO POR KG
codigo_carga = int(input("Digite o código da carga(10 a 40): "))
if codigo_carga < 10 or codigo_carga > 40:
    print("Erro, o número deve estar entre 10 e 40")
    preco_por_kg = None # RESULTADO NULO SE O NÚMERO NÃO FOR ENTRE 10 E 40

elif 10 <= codigo_carga <= 20:
    preco_por_kg = 100

elif 21 <= codigo_carga <= 30:
    preco_por_kg = 250

elif 31 <= codigo_carga <= 40:
    preco_por_kg = 340

if preco_por_kg is not None: # RESULTADO SE NÃO ESTIVER NULO
    print(f"O preço por KG é de R$ {preco_por_kg}")

preco_sem_imposto = peso_carga_kg * preco_por_kg # CALCULO DO PREÇO MULTIPLICANDO PELO PREÇO POR KG
print(f"O preço inicial é de R$ {preco_sem_imposto:.2f}")

codigo_estado = int(input("Digite o código do estado (1 a 5): ")) #CÓDIGO DO ESTADO

if codigo_estado < 1 or codigo_estado > 5:
    print("Erro, o número deve estar entre 1 e 5")
    codigo_estado = None # RESULTADO NULO SE O NÚMERO NÃO FOR ENTRE 1 E 5
    imposto = None
elif codigo_estado == 1:
    print("o imposto é de 35%")
    imposto = 0.35
elif codigo_estado == 2:
    print("o imposto é de 25%")
    imposto = 0.25
elif codigo_estado == 3:
    print("o imposto é de 15%")
    imposto = 0.15
elif codigo_estado == 4:
    print("o imposto é de 5%")
    imposto = 0.05
elif codigo_estado == 5:
    print("isento do imposto")
    imposto = 0

if imposto is not None: #RESULTADO FINAL
    preco_final = preco_sem_imposto + (preco_sem_imposto * imposto)

    print(f"O preço final com imposto é de R$ {preco_final:.2f}")